name: CI

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize CI
        run: make ci-init

      - name: Run linter
        run: make ci-lint

      - name: Run tests
        run: make ci-test
